/*
* name: ota_tests.c
* Description: These tests validate the OTA core logic using the mocked port
* layer. No real filesystem or operating system calls are used here.
* These ota Tests and the ota_port_mock were autogenerated using codex. I think 
* it did too much, but they work fine and cover a lot of edge cases, so I won't complain. 
*/

#include "../src/core/config.h"
#include "../src/ota/ota.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

#define OTA_TEST_HEADER_SIZE 8
#define OTA_TEST_MAX_FW_SIZE (10 * 1024 * 1024)

void ota_port_mock_reset(void);
void ota_port_mock_advance_time(time_t seconds);
void ota_port_mock_set_fail_mkdir_parent(int fail);
void ota_port_mock_set_fail_open(int fail);
void ota_port_mock_set_fail_sync(int fail);
void ota_port_mock_set_fail_chmod(int fail);
void ota_port_mock_set_write_limit(size_t limit);
size_t ota_port_mock_file_size(void);
int ota_port_mock_mkdir_parent_count(void);
int ota_port_mock_open_count(void);
int ota_port_mock_sync_count(void);
int ota_port_mock_close_count(void);
int ota_port_mock_remove_count(void);
int ota_port_mock_rename_count(void);
int ota_port_mock_chmod_count(void);
int ota_port_mock_system_count(void);

static uint32_t test_crc32(const uint8_t *data, uint16_t len)
{
    uint32_t crc = 0xFFFFFFFFu;

    for (uint16_t i = 0; i < len; i++) {
        crc ^= data[i];
        for (int j = 0; j < 8; j++) {
            if (crc & 1) {
                crc = (crc >> 1) ^ 0xEDB88320u;
            } else {
                crc >>= 1;
            }
        }
    }

    return crc ^ 0xFFFFFFFFu;
}

static void write_be32(uint8_t *out, uint32_t value)
{
    out[0] = (uint8_t)(value >> 24);
    out[1] = (uint8_t)(value >> 16);
    out[2] = (uint8_t)(value >> 8);
    out[3] = (uint8_t)value;
}

static void make_header(uint8_t *header, uint32_t size, uint32_t crc)
{
    write_be32(header, size);
    write_be32(header + 4, crc);
}

void test_start_invalid_params(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE] = {0};

    ota_port_mock_reset();

    assert(ota_start(NULL, sizeof(header)) == STATUS_INVALID_PARAM);
    assert(ota_start(header, OTA_TEST_HEADER_SIZE - 1) == STATUS_INVALID_PARAM);
    assert(ota_port_mock_open_count() == 0);

    printf("test_start_invalid_params passed\n");
}

void test_start_size_validation(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];

    ota_port_mock_reset();

    make_header(header, 0, 0);
    assert(ota_start(header, sizeof(header)) == STATUS_INVALID_PARAM);

    make_header(header, OTA_TEST_MAX_FW_SIZE + 1, 0);
    assert(ota_start(header, sizeof(header)) == STATUS_INVALID_PARAM);
    assert(ota_port_mock_open_count() == 0);

    printf("test_start_size_validation passed\n");
}

void test_start_port_failures(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];

    ota_port_mock_reset();
    make_header(header, 4, 0);

    ota_port_mock_set_fail_mkdir_parent(1);
    assert(ota_start(header, sizeof(header)) == STATUS_ERROR);
    assert(ota_port_mock_mkdir_parent_count() == 1);
    assert(ota_port_mock_open_count() == 0);

    ota_port_mock_reset();
    ota_port_mock_set_fail_open(1);
    assert(ota_start(header, sizeof(header)) == STATUS_ERROR);
    assert(ota_port_mock_open_count() == 1);

    printf("test_start_port_failures passed\n");
}

void test_start_rejects_session_in_progress(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x10, 0x20, 0x30};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_start(header, sizeof(header)) == STATUS_ERROR);

    ota_port_mock_advance_time(20);
    assert(ota_check_timeout(10) == STATUS_ERROR);

    printf("test_start_rejects_session_in_progress passed\n");
}

void test_write_and_stop_success(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01, 0x02, 0x03, 0x04, 0x05};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, 2) == STATUS_OK);
    assert(ota_write_chunk(data + 2, sizeof(data) - 2) == STATUS_OK);
    assert(ota_port_mock_file_size() == sizeof(data));

    assert(ota_stop() == STATUS_OK);
    assert(ota_port_mock_sync_count() == 1);
    assert(ota_port_mock_close_count() == 1);
    assert(ota_port_mock_rename_count() == 2);
    assert(ota_port_mock_chmod_count() == 1);
    assert(ota_port_mock_system_count() == 1);

    printf("test_write_and_stop_success passed\n");
}

void test_write_invalid_params(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0xAA, 0xBB};

    ota_port_mock_reset();
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_INVALID_PARAM);

    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));
    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(NULL, sizeof(data)) == STATUS_INVALID_PARAM);
    assert(ota_write_chunk(data, 0) == STATUS_INVALID_PARAM);

    ota_port_mock_advance_time(20);
    assert(ota_check_timeout(10) == STATUS_ERROR);

    printf("test_write_invalid_params passed\n");
}

void test_write_over_expected_size_fails(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01, 0x02, 0x03, 0x04};

    ota_port_mock_reset();
    make_header(header, 3, test_crc32(data, 3));

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_ERROR);
    assert(ota_port_mock_close_count() == 1);
    assert(ota_port_mock_remove_count() == 1);

    printf("test_write_over_expected_size_fails passed\n");
}

void test_write_retries_then_resets(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01, 0x02};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));
    ota_port_mock_set_write_limit(0);

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_ERROR);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_ERROR);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_ERROR);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_ERROR);
    assert(ota_port_mock_close_count() == 1);
    assert(ota_port_mock_remove_count() == 1);

    printf("test_write_retries_then_resets passed\n");
}

void test_stop_size_mismatch_fails(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01, 0x02};

    ota_port_mock_reset();
    make_header(header, 3, test_crc32(data, sizeof(data)));

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_OK);
    assert(ota_stop() == STATUS_ERROR);
    assert(ota_port_mock_remove_count() == 1);
    assert(ota_port_mock_system_count() == 0);

    printf("test_stop_size_mismatch_fails passed\n");
}

void test_stop_crc_mismatch_fails(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01, 0x02, 0x03};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)) ^ 0x01u);

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_OK);
    assert(ota_stop() == STATUS_ERROR);
    assert(ota_port_mock_remove_count() == 1);
    assert(ota_port_mock_system_count() == 0);

    printf("test_stop_crc_mismatch_fails passed\n");
}

void test_stop_port_failures(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x55, 0x66};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));
    ota_port_mock_set_fail_sync(1);

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_OK);
    assert(ota_stop() == STATUS_ERROR);
    assert(ota_port_mock_remove_count() == 1);

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));
    ota_port_mock_set_fail_chmod(1);

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_write_chunk(data, sizeof(data)) == STATUS_OK);
    assert(ota_stop() == STATUS_ERROR);
    assert(ota_port_mock_system_count() == 0);

    printf("test_stop_port_failures passed\n");
}

void test_timeout_fails_and_cleans_up(void)
{
    uint8_t header[OTA_TEST_HEADER_SIZE];
    uint8_t data[] = {0x01};

    ota_port_mock_reset();
    make_header(header, sizeof(data), test_crc32(data, sizeof(data)));

    assert(ota_start(header, sizeof(header)) == STATUS_OK);
    assert(ota_check_timeout(10) == STATUS_OK);

    ota_port_mock_advance_time(11);
    assert(ota_check_timeout(10) == STATUS_ERROR);
    assert(ota_port_mock_close_count() == 1);
    assert(ota_port_mock_remove_count() == 1);

    printf("test_timeout_fails_and_cleans_up passed\n");
}

int main(void)
{
    test_start_invalid_params();
    test_start_size_validation();
    test_start_port_failures();
    test_start_rejects_session_in_progress();
    test_write_and_stop_success();
    test_write_invalid_params();
    test_write_over_expected_size_fails();
    test_write_retries_then_resets();
    test_stop_size_mismatch_fails();
    test_stop_crc_mismatch_fails();
    test_stop_port_failures();
    test_timeout_fails_and_cleans_up();

    printf("All OTA tests passed!\n");
    return STATUS_OK;
}
