/*
* name: tcp_protocol_server_test.c
* Description: These tests validate the protocol command dispatch logic using
* simple mocks for OTA operations and TCP send
* These tests were autogenerated using codex.
*/ 

#include "../src/comms/tcp_protocol_server.h"
#include "../src/core/config.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

void tcp_server_mock_reset(void);
int tcp_server_mock_send_count(void);
int tcp_server_mock_send_fd(void);
int tcp_server_mock_send_len(void);
uint8_t *tcp_server_mock_send_buffer(void);

static int mock_start_count;
static int mock_write_count;
static int mock_stop_count;
static int mock_timeout_count;
static STATUS_E mock_start_result;
static STATUS_E mock_write_result;
static STATUS_E mock_stop_result;
static STATUS_E mock_timeout_result;
static uint16_t mock_last_len;
static uint8_t mock_last_data[FRAME_MAX_DATA];

static STATUS_E mock_ota_start(uint8_t *data, uint16_t len)
{
    mock_start_count++;
    mock_last_len = len;
    memcpy(mock_last_data, data, len);
    return mock_start_result;
}

static STATUS_E mock_ota_write(uint8_t *data, uint16_t len)
{
    mock_write_count++;
    mock_last_len = len;
    memcpy(mock_last_data, data, len);
    return mock_write_result;
}

static STATUS_E mock_ota_stop(void)
{
    mock_stop_count++;
    return mock_stop_result;
}

static STATUS_E mock_ota_timeout(int timeout_sec)
{
    mock_timeout_count++;
    mock_last_len = (uint16_t)timeout_sec;
    return mock_timeout_result;
}

static ota_ops_t mock_ota = {
    .start = mock_ota_start,
    .write = mock_ota_write,
    .stop = mock_ota_stop,
    .timeout = mock_ota_timeout
};

static void reset_mocks(void)
{
    tcp_server_mock_reset();

    mock_start_count = 0;
    mock_write_count = 0;
    mock_stop_count = 0;
    mock_timeout_count = 0;
    mock_start_result = STATUS_OK;
    mock_write_result = STATUS_OK;
    mock_stop_result = STATUS_OK;
    mock_timeout_result = STATUS_OK;
    mock_last_len = 0;
    memset(mock_last_data, 0, sizeof(mock_last_data));
}

static void make_frame(frame_t *frame, uint8_t cmd, uint8_t seq,
                       uint8_t *data, uint16_t len)
{
    memset(frame, 0, sizeof(*frame));
    frame->sof = FRAME_SOF;
    frame->cmd = cmd;
    frame->seq = seq;
    frame->len = len;

    if (data != NULL && len > 0) {
        memcpy(frame->data, data, len);
    }
}

static void assert_response(uint8_t cmd, uint8_t seq)
{
    frame_t decoded;
    int consumed;
    STATUS_E res;

    assert(tcp_server_mock_send_count() == 1);
    res = frame_decode(tcp_server_mock_send_buffer(),
                       tcp_server_mock_send_len(),
                       &decoded,
                       &consumed);

    assert(res == STATUS_OK);
    assert(decoded.cmd == cmd);
    assert(decoded.len == 1);
    assert(decoded.data[0] == seq);
}

void test_ping_sends_ack(void)
{
    frame_t frame;

    reset_mocks();
    make_frame(&frame, CMD_PING, 7, NULL, 0);

    protocol_handler(123, &frame, &mock_ota);

    assert(tcp_server_mock_send_fd() == 123);
    assert_response(CMD_ACK, 7);
    assert(mock_start_count == 0);
    assert(mock_write_count == 0);
    assert(mock_stop_count == 0);

    printf("test_ping_sends_ack passed\n");
}

void test_unknown_command_sends_nack(void)
{
    frame_t frame;

    reset_mocks();
    make_frame(&frame, 0x55, 8, NULL, 0);

    protocol_handler(123, &frame, &mock_ota);

    assert_response(CMD_NACK, 8);

    printf("test_unknown_command_sends_nack passed\n");
}

void test_ota_start_success_sends_ack(void)
{
    frame_t frame;
    uint8_t data[] = {0x01, 0x02, 0x03};

    reset_mocks();
    make_frame(&frame, CMD_OTA_START, 9, data, sizeof(data));

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_start_count == 1);
    assert(mock_last_len == sizeof(data));
    assert(memcmp(mock_last_data, data, sizeof(data)) == 0);
    assert_response(CMD_ACK, 9);

    printf("test_ota_start_success_sends_ack passed\n");
}

void test_ota_start_error_sends_nack(void)
{
    frame_t frame;
    uint8_t data[] = {0x10};

    reset_mocks();
    mock_start_result = STATUS_ERROR;
    make_frame(&frame, CMD_OTA_START, 10, data, sizeof(data));

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_start_count == 1);
    assert_response(CMD_NACK, 10);

    printf("test_ota_start_error_sends_nack passed\n");
}

void test_ota_data_dispatch(void)
{
    frame_t frame;
    uint8_t data[] = {0xAA, 0xBB};

    reset_mocks();
    make_frame(&frame, CMD_OTA_DATA, 11, data, sizeof(data));

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_write_count == 1);
    assert(mock_last_len == sizeof(data));
    assert(memcmp(mock_last_data, data, sizeof(data)) == 0);
    assert_response(CMD_ACK, 11);

    printf("test_ota_data_dispatch passed\n");
}

void test_ota_data_error_sends_nack(void)
{
    frame_t frame;
    uint8_t data[] = {0xAA};

    reset_mocks();
    mock_write_result = STATUS_ERROR;
    make_frame(&frame, CMD_OTA_DATA, 12, data, sizeof(data));

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_write_count == 1);
    assert_response(CMD_NACK, 12);

    printf("test_ota_data_error_sends_nack passed\n");
}

void test_ota_end_success_sends_ack(void)
{
    frame_t frame;

    reset_mocks();
    make_frame(&frame, CMD_OTA_END, 13, NULL, 0);

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_stop_count == 1);
    assert_response(CMD_ACK, 13);

    printf("test_ota_end_success_sends_ack passed\n");
}

void test_ota_end_error_sends_nack(void)
{
    frame_t frame;

    reset_mocks();
    mock_stop_result = STATUS_ERROR;
    make_frame(&frame, CMD_OTA_END, 14, NULL, 0);

    protocol_handler(123, &frame, &mock_ota);

    assert(mock_stop_count == 1);
    assert_response(CMD_NACK, 14);

    printf("test_ota_end_error_sends_nack passed\n");
}

void test_protocol_check_timeout(void)
{
    reset_mocks();
    mock_timeout_result = STATUS_TIMEOUT;

    assert(protocol_check_timeout(30, &mock_ota) == STATUS_TIMEOUT);
    assert(mock_timeout_count == 1);
    assert(mock_last_len == 30);

    printf("test_protocol_check_timeout passed\n");
}

int main(void)
{
    test_ping_sends_ack();
    test_unknown_command_sends_nack();
    test_ota_start_success_sends_ack();
    test_ota_start_error_sends_nack();
    test_ota_data_dispatch();
    test_ota_data_error_sends_nack();
    test_ota_end_success_sends_ack();
    test_ota_end_error_sends_nack();
    test_protocol_check_timeout();

    printf("All tcp_protocol_server tests passed!\n");
    return STATUS_OK;
}
